//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial_2.Models
{
    using System.ComponentModel.DataAnnotations.Schema;

    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.ComponentModel.DataAnnotations;

    public partial class Pesaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pesaje()
        {
            this.FotoPesaje = new HashSet<FotoPesaje>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]

        public int id { get; set; }
        public System.DateTime FechaPesaje { get; set; }
        public string PlacaCamion { get; set; }
        public float Peso { get; set; }
        public string Estacion { get; set; }


        [JsonIgnore]
        public virtual Camion Camion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotoPesaje> FotoPesaje { get; set; }
    }
}
